name: PipelineFlask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-ct4quad6l47c73fap9hg
        api-key: ${{ secrets.RENDER_API_KEY }} 

    - name: Deploy to EC2 - AWS
      env:
        SSH_PRIVATE_KEY: ${{ MIIEpAIBAAKCAQEAw5nRFT9Nz+DRDro0zv+foD8oj+FZr7er2Lg25iubE/dEd0mc
q8lAgTHCWjdxZrhH/FvhwfGjF/xgXjj3Zv+QMVwT4EO7Zp/CcWtQvbr5JVQMhJ4L
AZTg8RIBnD5Y5VQqbU4vp3087eTcPzJ96JYYCpq3TzOdguoe8a7DpSVD+cs8Qz4E
c4Q8UbEDG49YtvX1BzhiQl2m1mUCLRjUlV1rUTJqorUYz1IVId+pz4EK0M4Odgpy
OoejPy2uxEUcz8C+Ez/8p9TIDKG2AkBseRG9Y7ZiR07qqsRcSEm5gThfvxEvOv9c
bTqLFrqQBSaQFhPTqe/HKmOXUp2FGqqjF06tyQIDAQABAoIBAQCc9+ZbZ7bZGPCM
IhBZAbinD6hMdqrTodENlR+xbNMBndBa7j8FePcD9tuiLJYbuc1DDrVIP9MDX6wy
UQLxrCuaAOuOcKyGObT/8gAUkmR4eU+maXIprcEqlKmoKjyKpRV7LGB/x7hKrPu2
151FNpZKhEiRDbncomd8yiQFdrdrUC8IFIRd03xXsU3cqW9F6Jklge6Q6Wjcud7R
byVD4t2Ylyuv2iKA+IxpU4FTg/CG+0iFBLKg+c0VYWqqqbCNEjTT5fmv4U9uTzND
JWmGC1fY/R6RxDt2cMS+8ca4W0EYbD3f82PwiVyDznMrz/ZV7zAvuDMF6YwthsYw
TeTJvyDRAoGBAOt1xGXZdFc7kMLq5nXmBlB3h9xLKoU2XglEOwrpoiW9t8Mx3VbK
r56698Sa7kdiCsSNDHgR7j4fCUOuaooCOFn1b2fvoAgHiJLx8/jnwTHwhnaa7G4o
B4cYlkZBEmumMa1ecE3y6nt6kBLPSH8auTn011uPZ/Sjg5QoJkSbsoNlAoGBANSp
7K/JmrZT5Gu3Tg/3Tsn1UvBnzmDv2M99cbWy9FE8j2I5T0FD+xvZ6YrRw+a7jzQL
JZJau6mTyJOpOPlZXVVD11bRxALFTj6FGjXDDBZ4j6c4qMSgFAUM7ywJk/zPyi5W
iK46EvBNDvVPv2ZiQvBHDWp/+tJ5MXjv41+yViSVAoGAHP5lbr02LD+zda0DL+Vh
RatSWXgQBlNJhQ6XzqIySz9vT2Pmg3d15K/VLqp9SODzvnw32tkqYw/jTig+Cjx3
v+wPCddh91smICIXDsFK8uFRTW2KS442TxZh+sisggD3AQguAAs3gHj5ILfRj4U0
5cQWeLnR7TftTeMbwzsA4lkCgYB3l6OR66cEd8MRzECq++Gj80EUDtxhaSAc9yeW
DbAVayAbFa17P3acX/xU48fuHnXWx5n2Zu333DLEzzpKBzZUd9VGbqpzAHAS+pkV
uL04ec4XNOa7xGXdvTtXIX/GgTfqvSEaEXCLEFqkG5fAROvt4Zcq2BO+fwcSQp00
OL72zQKBgQDcew0WeK6FyoK48OqDYLLANl3Io6x5V+0G070s5u/ZdG6sKxlfLzrC
gFrD1k7uQ424PtB1WHlHGU5uO6EnzOQSvQ9P+zyUo/yiRMkavmpfBGAkgTSPNCXQ
zYQwIaXTd64KYu2fRBRnFaTYcUbsrXsvg/43QSDjHYQDtuHZdhtiKA== }}
      run: |
        echo "Connecting to EC2..."
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-232-6-173.compute-1.amazonaws.com "
          cd treinoDevOps/; git pull; ./executar.sh"
