# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Render Deploy Action
      if: ${{ github.ref == 'refs/heads/dev' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'dev') }}
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-ct4quad6l47c73fap9hg
        api-key: rnd_CwlMDRDk1pUyIPlmh7aj9XrLwMuY

    - name: Deploy AWS
      if: ${{ github.ref == 'refs/heads/main' || (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') }}
      run: |
        echo "Connecting to EC2"
        echo "${{secrets.KEY}}" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-3-232-6-173.compute-1.amazonaws.com "
          cd testeDevOps/; git pull; ./iniciarApp.sh"
